///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DireccionRegistroFormModel {
/*
{
  "id": 1,
  "domicilio": "Republica de costa rica 325",
  "colonia": "Quintero",
  "cp": "45550",
  "cruces": "Rio seco y lerdo de tejada",
  "ciudad": "Tlaquepaque",
  "estado": "Jalisco",
  "cliente": 1
} 
*/

  String? domicilio;
  String? colonia;
  String? cp;
  String? cruces;
  String? ciudad;
  String? estado;
  int? cliente;

  DireccionRegistroFormModel({
    this.domicilio,
    this.colonia,
    this.cp,
    this.cruces,
    this.ciudad,
    this.estado,
    this.cliente,
  });
  DireccionRegistroFormModel.fromJson(Map<String, dynamic> json) {
    domicilio = json['domicilio']?.toString();
    colonia = json['colonia']?.toString();
    cp = json['cp']?.toString();
    cruces = json['cruces']?.toString();
    ciudad = json['ciudad']?.toString();
    estado = json['estado']?.toString();
    cliente = json['cliente']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['domicilio'] = domicilio;
    data['colonia'] = colonia;
    data['cp'] = cp;
    data['cruces'] = cruces;
    data['ciudad'] = ciudad;
    data['estado'] = estado;
    data['cliente'] = cliente;
    return data;
  }
}
