///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductoModel {
/*
{
  "id": 1,
  "nombre": "PRUEBA 1",
  "precio": 100,
  "existencia": 100,
  "createdAt": "2024-04-30T16:05:54.749Z",
  "updatedAt": "2024-04-30T16:05:56.870Z",
  "publishedAt": "2024-04-30T16:05:56.733Z"
} 
*/

  int? id;
  String? nombre;
  int? precio;
  int? existencia;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  ProductoModel({
    this.id,
    this.nombre,
    this.precio,
    this.existencia,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  ProductoModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    nombre = json['nombre']?.toString();
    precio = json['precio']?.toInt();
    existencia = json['existencia']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['nombre'] = nombre;
    data['precio'] = precio;
    data['existencia'] = existencia;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}
