///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ClienteSearchModelVentasProductos {
/*
{
  "producto": "RXC",
  "precio": "550",
  "cantidad": "2"
} 
*/

  String? producto;
  String? precio;
  String? cantidad;

  ClienteSearchModelVentasProductos({
    this.producto,
    this.precio,
    this.cantidad,
  });
  ClienteSearchModelVentasProductos.fromJson(Map<String, dynamic> json) {
    producto = json['producto']?.toString();
    precio = json['precio']?.toString();
    cantidad = json['cantidad']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['producto'] = producto;
    data['precio'] = precio;
    data['cantidad'] = cantidad;
    return data;
  }
}

class ClienteSearchModelVentas {
/*
{
  "id": 1,
  "productos": [
    {
      "producto": "RXC",
      "precio": "550",
      "cantidad": "2"
    }
  ],
  "fechaEntrega": "2023-10-10",
  "idPedido": "1P",
  "subTotal": 1100,
  "total": 1120,
  "estatus": "CALIDAD",
  "nota": "Hola,Mundo",
  "de": "10:00",
  "a": "15:00",
  "formaDePago": "COD",
  "createdAt": "2024-04-27T16:48:45.677Z",
  "updatedAt": "2024-04-27T17:03:15.170Z",
  "publishedAt": "2024-04-27T16:48:51.579Z"
} 
*/

  int? id;
  List<ClienteSearchModelVentasProductos?>? productos;
  String? fechaEntrega;
  String? idPedido;
  int? subTotal;
  int? total;
  String? estatus;
  String? nota;
  String? de;
  String? a;
  String? formaDePago;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  ClienteSearchModelVentas({
    this.id,
    this.productos,
    this.fechaEntrega,
    this.idPedido,
    this.subTotal,
    this.total,
    this.estatus,
    this.nota,
    this.de,
    this.a,
    this.formaDePago,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  ClienteSearchModelVentas.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    if (json['productos'] != null) {
      final v = json['productos'];
      final arr0 = <ClienteSearchModelVentasProductos>[];
      v.forEach((v) {
        arr0.add(ClienteSearchModelVentasProductos.fromJson(v));
      });
      productos = arr0;
    }
    fechaEntrega = json['fechaEntrega']?.toString();
    idPedido = json['idPedido']?.toString();
    subTotal = json['subTotal']?.toInt();
    total = json['total']?.toInt();
    estatus = json['estatus']?.toString();
    nota = json['nota']?.toString();
    de = json['de']?.toString();
    a = json['a']?.toString();
    formaDePago = json['formaDePago']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (productos != null) {
      final v = productos;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['productos'] = arr0;
    }
    data['fechaEntrega'] = fechaEntrega;
    data['idPedido'] = idPedido;
    data['subTotal'] = subTotal;
    data['total'] = total;
    data['estatus'] = estatus;
    data['nota'] = nota;
    data['de'] = de;
    data['a'] = a;
    data['formaDePago'] = formaDePago;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}

class ClienteSearchModelDirecciones {
/*
{
  "id": 1,
  "domicilio": "Republica de costa rica 325",
  "colonia": "Quintero",
  "cp": "45550",
  "cruces": "Rio seco y lerdo de tejada",
  "ciudad": "Tlaquepaque",
  "estado": "Jalisco",
  "createdAt": "2024-04-27T16:50:25.135Z",
  "updatedAt": "2024-04-27T16:51:35.878Z",
  "publishedAt": "2024-04-27T16:51:35.743Z"
} 
*/

  int? id;
  String? domicilio;
  String? colonia;
  String? cp;
  String? cruces;
  String? ciudad;
  String? estado;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  ClienteSearchModelDirecciones({
    this.id,
    this.domicilio,
    this.colonia,
    this.cp,
    this.cruces,
    this.ciudad,
    this.estado,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  ClienteSearchModelDirecciones.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    domicilio = json['domicilio']?.toString();
    colonia = json['colonia']?.toString();
    cp = json['cp']?.toString();
    cruces = json['cruces']?.toString();
    ciudad = json['ciudad']?.toString();
    estado = json['estado']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['domicilio'] = domicilio;
    data['colonia'] = colonia;
    data['cp'] = cp;
    data['cruces'] = cruces;
    data['ciudad'] = ciudad;
    data['estado'] = estado;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}

class ClienteSearchModel {
/*
{
  "id": 1,
  "nombre": "Juan Pablo Rizo Quintero",
  "telefono": "3319747514",
  "createdAt": "2024-04-27T16:43:32.128Z",
  "updatedAt": "2024-04-27T16:43:36.054Z",
  "publishedAt": "2024-04-27T16:43:35.911Z",
  "direcciones": [
    {
      "id": 1,
      "domicilio": "Republica de costa rica 325",
      "colonia": "Quintero",
      "cp": "45550",
      "cruces": "Rio seco y lerdo de tejada",
      "ciudad": "Tlaquepaque",
      "estado": "Jalisco",
      "createdAt": "2024-04-27T16:50:25.135Z",
      "updatedAt": "2024-04-27T16:51:35.878Z",
      "publishedAt": "2024-04-27T16:51:35.743Z"
    }
  ],
  "ventas": [
    {
      "id": 1,
      "productos": [
        {
          "producto": "RXC",
          "precio": "550",
          "cantidad": "2"
        }
      ],
      "fechaEntrega": "2023-10-10",
      "idPedido": "1P",
      "subTotal": 1100,
      "total": 1120,
      "estatus": "CALIDAD",
      "nota": "Hola,Mundo",
      "de": "10:00",
      "a": "15:00",
      "formaDePago": "COD",
      "createdAt": "2024-04-27T16:48:45.677Z",
      "updatedAt": "2024-04-27T17:03:15.170Z",
      "publishedAt": "2024-04-27T16:48:51.579Z"
    }
  ]
} 
*/

  int? id;
  String? nombre;
  String? telefono;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;
  List<ClienteSearchModelDirecciones?>? direcciones;
  List<ClienteSearchModelVentas?>? ventas;

  ClienteSearchModel({
    this.id,
    this.nombre,
    this.telefono,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
    this.direcciones,
    this.ventas,
  });
  ClienteSearchModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    nombre = json['nombre']?.toString();
    telefono = json['telefono']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
    if (json['direcciones'] != null) {
      final v = json['direcciones'];
      final arr0 = <ClienteSearchModelDirecciones>[];
      v.forEach((v) {
        arr0.add(ClienteSearchModelDirecciones.fromJson(v));
      });
      direcciones = arr0;
    }
    if (json['ventas'] != null) {
      final v = json['ventas'];
      final arr0 = <ClienteSearchModelVentas>[];
      v.forEach((v) {
        arr0.add(ClienteSearchModelVentas.fromJson(v));
      });
      ventas = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['nombre'] = nombre;
    data['telefono'] = telefono;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    if (direcciones != null) {
      final v = direcciones;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['direcciones'] = arr0;
    }
    if (ventas != null) {
      final v = ventas;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['ventas'] = arr0;
    }
    return data;
  }
}
