///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VentaRegistroFormModelProductos {
/*
{
  "producto": "RXC",
  "precio": 550.2,
  "cantidad": 2
} 
*/

  String? producto;
  double? precio;
  int? cantidad;

  VentaRegistroFormModelProductos({
    this.producto,
    this.precio,
    this.cantidad,
  });
  VentaRegistroFormModelProductos.fromJson(Map<String, dynamic> json) {
    producto = json['producto']?.toString();
    precio = json['precio']?.toDouble();
    cantidad = json['cantidad']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['producto'] = producto;
    data['precio'] = precio;
    data['cantidad'] = cantidad;
    return data;
  }
}

class VentaRegistroFormModel {
/*
{
  "id": 1,
  "productos": [
    {
      "producto": "RXC",
      "precio": 550.2,
      "cantidad": 2
    }
  ],
  "fechaEntrega": "2023-10-10",
  "idPedido": "1P",
  "subTotal": 1100.1,
  "total": 1120.1,
  "estatus": "CALIDAD",
  "nota": "Hola,Mundo",
  "de": "10:00",
  "a": "15:00",
  "formaDePago": "COD",
  "cliente": 1,
  "direccion": 1,
  "vendedor": 1
} 
*/

  List<VentaRegistroFormModelProductos?>? productos;
  String? fechaEntrega;
  String? idPedido;
  double? subTotal;
  double? total;
  String? estatus;
  String? nota;
  String? de;
  String? a;
  String? formaDePago;
  int? cliente;
  int? direccion;
  int? vendedor;

  VentaRegistroFormModel({
    this.productos,
    this.fechaEntrega,
    this.idPedido,
    this.subTotal,
    this.total,
    this.estatus,
    this.nota,
    this.de,
    this.a,
    this.formaDePago,
    this.cliente,
    this.direccion,
    this.vendedor,
  });
  VentaRegistroFormModel.fromJson(Map<String, dynamic> json) {
    if (json['productos'] != null) {
      final v = json['productos'];
      final arr0 = <VentaRegistroFormModelProductos>[];
      v.forEach((v) {
        arr0.add(VentaRegistroFormModelProductos.fromJson(v));
      });
      productos = arr0;
    }
    fechaEntrega = json['fechaEntrega']?.toString();
    idPedido = json['idPedido']?.toString();
    subTotal = json['subTotal']?.toDouble();
    total = json['total']?.toDouble();
    estatus = json['estatus']?.toString();
    nota = json['nota']?.toString();
    de = json['de']?.toString();
    a = json['a']?.toString();
    formaDePago = json['formaDePago']?.toString();
    cliente = json['cliente']?.toInt();
    direccion = json['direccion']?.toInt();
    vendedor = json['vendedor']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};

    if (productos != null) {
      final v = productos;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['productos'] = arr0;
    }
    data['fechaEntrega'] = fechaEntrega;
    data['idPedido'] = idPedido;
    data['subTotal'] = subTotal;
    data['total'] = total;
    data['estatus'] = estatus;
    data['nota'] = nota;
    data['de'] = de;
    data['a'] = a;
    data['formaDePago'] = formaDePago;
    data['cliente'] = cliente;
    data['direccion'] = direccion;
    data['vendedor'] = vendedor;
    return data;
  }
}
